### ISSUE TITLE
Predicate should be hasChemicalSymbol instead of hasSymbol

### ISSUE THREAD

**Issue by NinadBhat** [pyscal/atomRDF#109]
When deleting atoms, and inserting substitutions and interstitials, atomRDF currently sets the predicate as hasSymbol. It should be hasChemicalSymbol instead.

**Comment by NinadBhat** [comment]
@srmnitc: I have created pull request (#110) for this.

**Comment by srmnitc** [comment]
@NinadBhat thanks, merged!
