### ISSUE TITLE
Tracking modifications

### ISSUE THREAD

**Issue by aazocar** [pyscal/atomRDF#156]
When using `structure.modify.repeat`, the new "repeated" structure is not tracked or added to the kg. 

The triples regarding the repetition, as well as the changes to the box and number of atoms should be added.

**Comment by GuojingHuangAa** [comment]
Hello Sarath, thanks for you efforts. I have reinstalled my atomRDF. However, I could not see the changes in structure.py (also in the repo) file and the repeated structure still can not be annotated. Could you please give me a few instructions of that. Thank you so much.
